from alembic import op
import sqlalchemy as sa
revision="0001_initial"; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("vehicles",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("brand",sa.String(80),nullable=False,index=True),sa.Column("model",sa.String(120),nullable=False,index=True),sa.Column("price",sa.BigInteger(),nullable=False),sa.Column("year",sa.Integer(),nullable=False),sa.Column("description",sa.Text(),nullable=False,server_default=""),sa.Column("photo_url",sa.String(1000)),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table("managers",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("name",sa.String(160),nullable=False),sa.Column("telegram_id",sa.BigInteger()),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table("leads",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("telegram_id",sa.BigInteger(),nullable=False,index=True),sa.Column("name",sa.String(160),nullable=False),sa.Column("phone",sa.String(40),nullable=False),sa.Column("vehicle_id",sa.Integer(),sa.ForeignKey("vehicles.id")),sa.Column("manager_id",sa.Integer(),sa.ForeignKey("managers.id")),sa.Column("source",sa.String(40),nullable=False,server_default="telegram"),sa.Column("status",sa.String(40),nullable=False,server_default="new"),sa.Column("created_at",sa.DateTime(),nullable=False,server_default=sa.func.now()))
    op.create_table("test_drives",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("telegram_id",sa.BigInteger(),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("phone",sa.String(40),nullable=False),sa.Column("vehicle_id",sa.Integer(),sa.ForeignKey("vehicles.id")),sa.Column("preferred_time",sa.String(100),nullable=False),sa.Column("status",sa.String(40),nullable=False,server_default="new"),sa.Column("created_at",sa.DateTime(),nullable=False,server_default=sa.func.now()))
    op.create_table("promotions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("title",sa.String(200),nullable=False),sa.Column("text",sa.Text(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(),nullable=False,server_default=sa.func.now()))
def downgrade():
    for t in ["test_drives","leads","managers","promotions","vehicles"]: op.drop_table(t)
